version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    command: sh -c "npm ci && npx nx run api:serve"
    env_file: .env
    environment:
      NODE_ENV: development
      DATABASE_URL: "mongodb://db:27017/apptit_dev"
      REDIS_URL: "redis://redis:6379"
    ports:
      - "4000:4000"
    volumes:
      - .:/repo
      - /repo/node_modules
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    command: sh -c "npm ci && npx nx run web:dev"
    env_file: .env
    environment:
      NODE_ENV: development
      NEXT_TELEMETRY_DISABLED: "1"
      API_URL: "http://api:4000"
    ports:
      - "3000:3000"
    volumes:
      - .:/repo
      - /repo/node_modules
    depends_on:
      api:
        condition: service_started

  db:
    image: mongo:7
    container_name: apptit_mongo
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    container_name: apptit_redis
    ports:
      - "6379:6379"

networks:
  default:
    name: apptit_net
