version: "3.9"

services:
  # API (NestJS)
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    container_name: apptit-api
    env_file:
      - .env
    depends_on:
      - redis-users
      - redis-search
      - mongodb-users
      - mongodb-stock
      - kafka
    networks:
      - backend
    ports:
      - "4000:4000"

  # Landing (Next.js)
  landing:
    build:
      context: .
      dockerfile: ./apps/landing/Dockerfile
    container_name: apptit-landing
    env_file:
      - .env
    depends_on:
      - api
    networks:
      - frontend
    ports:
      - "3000:3000"

  # Dashboard (Next.js)
  dashboard:
    build:
      context: .
      dockerfile: ./apps/dashboard/Dockerfile
    container_name: apptit-dashboard
    env_file:
      - .env
    depends_on:
      - api
    networks:
      - frontend
    ports:
      - "3001:3000"

  # Redis for Users
  redis-users:
    image: redis:alpine
    container_name: redis-users
    networks:
      - backend
    volumes:
      - redis-data-users:/data
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"

  # Redis for Search
  redis-search:
    image: redis:alpine
    container_name: redis-search
    networks:
      - backend
    volumes:
      - redis-data-search:/data
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6380:6379"

  # MongoDB for Users
  mongodb-users:
    image: mongo:latest
    container_name: mongodb-users
    networks:
      - backend
    volumes:
      - mongo-data-users:/data/db
    ports:
      - "27017:27017"

  # MongoDB for Stock
  mongodb-stock:
    image: mongo:latest
    container_name: mongodb-stock
    networks:
      - backend
    volumes:
      - mongo-data-stock:/data/db
    ports:
      - "27018:27017"

  # Kafka (Bitnami)
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - backend
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
  # Zookeeper
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - backend
    ports:
      - "2181:2181"

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  redis-data-users:
  redis-data-search:
  mongo-data-users:
  mongo-data-stock:
